# Generated by Django 5.1.7 on 2025-03-19 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscompany',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='company_id',
        ),
        migrations.AddField(
            model_name='buscompany',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus_app.buscompany'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
