# Generated by Django 5.1.3 on 2024-11-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0002_buscompany_route_stoppage_bus_cashflow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
