# Generated by Django 5.1.3 on 2024-11-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppage',
            name='vehicle_id',
        ),
    ]
