# Generated by Django 5.1.3 on 2024-11-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0005_remove_stoppage_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppage',
            name='location',
        ),
        migrations.AddField(
            model_name='stoppage',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='stoppage',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stoppage',
            name='queue_length',
            field=models.IntegerField(default=0),
        ),
    ]
