# Generated by Django 5.1.3 on 2024-11-21 00:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0006_remove_stoppage_location_stoppage_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='depart_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_from_stoppage', to='bus_app.stoppage'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_to_stoppage', to='bus_app.stoppage'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_no',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='OngoingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.PositiveIntegerField(editable=False)),
                ('arrival_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.bus')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stoppage', to='bus_app.stoppage')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
