# Generated by Django 5.1.6 on 2025-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0007_remove_trip_depart_time_trip_distance_trip_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingtrip',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
    ]
