# Generated by Django 5.1.6 on 2025-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0008_alter_ongoingtrip_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_route',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
