# Generated by Django 5.1.6 on 2025-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0009_profile_in_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='in_route',
            field=models.BooleanField(default=False),
        ),
    ]
