# Generated by Django 5.1.6 on 2025-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0010_alter_profile_in_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoingtrip',
            old_name='bus',
            new_name='bus_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
