# Generated by Django 5.1.6 on 2025-03-11 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0012_driverprofile_drivertrip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='verified_drivers/')),
                ('image_2', models.ImageField(upload_to='verified_drivers/')),
                ('image_3', models.ImageField(upload_to='verified_drivers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
