# Generated by Django 5.1.7 on 2025-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0013_verifieddriverprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='name',
            new_name='drivername',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='company_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='email',
            field=models.EmailField(default=12, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
