# Generated by Django 5.1.7 on 2025-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0014_rename_name_driverprofile_drivername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieddriverprofile',
            name='image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifieddriverprofile',
            name='image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifieddriverprofile',
            name='image_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
