# Generated by Django 5.1.7 on 2025-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0015_alter_verifieddriverprofile_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifieddriverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='verifieddriverprofile',
            name='user_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
